$ErrorActionPreference = 'Stop'

$ctlDir = Join-Path $PSScriptRoot 'ctl'
New-Item -ItemType Directory -Force -Path $ctlDir | Out-Null

$templates = @{
  'p_72_panstwo.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_panstwo.csv'
INTO TABLE P_72_PANSTWO
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_PANSTWA,
  NAZWA_PANSTWA "RTRIM(:NAZWA_PANSTWA, CHR(13))"
)
"@
  'p_72_wojewodztwo.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_wojewodztwo.csv'
INTO TABLE P_72_WOJEWODZTWO
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_WOJEWODZTWO,
  ID_PANSTWA,
  NAZWA_WOJEWODZTWA "RTRIM(:NAZWA_WOJEWODZTWA, CHR(13))"
)
"@
  'p_72_miasto.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_miasto.csv'
INTO TABLE P_72_MIASTO
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_MIASTA,
  ID_WOJEWODZTWO,
  NAZWA_MIASTA "RTRIM(:NAZWA_MIASTA, CHR(13))"
)
"@
  'p_72_ulica.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_ulica.csv'
INTO TABLE P_72_ULICA
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_ULICA,
  ID_MIASTA,
  NAZWA_ULICY "RTRIM(:NAZWA_ULICY, CHR(13))"
)
"@
  'p_72_oddzial.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_oddzial.csv'
INTO TABLE P_72_ODDZIAL
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_ODDZIAL,
  NAZWA_ODDZIALU "RTRIM(:NAZWA_ODDZIALU, CHR(13))",
  TELEFON "RTRIM(:TELEFON, CHR(13))",
  EMAIL "RTRIM(:EMAIL, CHR(13))",
  GODZINY_OTWARCIA "RTRIM(:GODZINY_OTWARCIA, CHR(13))",
  NUMER_BUDYNKU "RTRIM(:NUMER_BUDYNKU, CHR(13))",
  ID_ULICA,
  KOD_POCZTOWY "RTRIM(:KOD_POCZTOWY, CHR(13))"
)
"@
  'p_72_stanowisko.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_stanowisko.csv'
INTO TABLE P_72_STANOWISKO
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_STANOWISKO,
  NAZWA_STANOWISKA "RTRIM(:NAZWA_STANOWISKA, CHR(13))",
  OPIS "RTRIM(:OPIS, CHR(13))",
  STAWKA_GODZINOWA
)
"@
  'p_72_pracownik.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_pracownik.csv'
INTO TABLE P_72_PRACOWNIK
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_PRACOWNIK,
  ID_ODDZIAL,
  ID_STANOWISKO,
  IMIE "RTRIM(:IMIE, CHR(13))",
  NAZWISKO "RTRIM(:NAZWISKO, CHR(13))",
  PESEL "RTRIM(:PESEL, CHR(13))",
  TELEFON "RTRIM(:TELEFON, CHR(13))",
  EMAIL "RTRIM(:EMAIL, CHR(13))",
  DATA_ZATRUDNIENIA DATE "YYYY-MM-DD"
)
"@
  'p_72_kategoria.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_kategoria.csv'
INTO TABLE P_72_KATEGORIA
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_KATEGORIA,
  NAZWA_KATEGORII "RTRIM(:NAZWA_KATEGORII, CHR(13))",
  OPIS "RTRIM(:OPIS, CHR(13))",
  STAWKA_BAZOWA_NETTO
)
"@
  'p_72_kolor.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_kolor.csv'
INTO TABLE P_72_KOLOR
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_KOLOR,
  NAZWA_KOLORU "RTRIM(:NAZWA_KOLORU, CHR(13))"
)
"@
  'p_72_marka.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_marka.csv'
INTO TABLE P_72_MARKA
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_MARKA,
  NAZWA_MARKI "RTRIM(:NAZWA_MARKI, CHR(13))"
)
"@
  'p_72_model.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_model.csv'
INTO TABLE P_72_MODEL
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_MODEL,
  NAZWA_MODELU "RTRIM(:NAZWA_MODELU, CHR(13))",
  ID_MARKA
)
"@
  'p_72_typ_paliwa.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_typ_paliwa.csv'
INTO TABLE P_72_TYP_PALIWA
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_TYPU_PALIWA,
  NAZWA_PALIWA "RTRIM(:NAZWA_PALIWA, CHR(13))"
)
"@
  'p_72_typ_skrzyni.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_typ_skrzyni.csv'
INTO TABLE P_72_TYP_SKRZYNI
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_TYPU_SKRZYNI,
  NAZWA_SKRZYNI "RTRIM(:NAZWA_SKRZYNI, CHR(13))"
)
"@
  'p_72_samochod.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_samochod.csv'
INTO TABLE P_72_SAMOCHOD
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_SAMOCHOD,
  ID_ODDZIAL,
  ID_TYPU_PALIWA,
  ID_KOLOR,
  ID_KATEGORIA,
  ID_MODEL,
  ID_TYPU_SKRZYNI,
  NUMER_REJESTRACYJNY "RTRIM(:NUMER_REJESTRACYJNY, CHR(13))",
  NUMER_VIN "RTRIM(:NUMER_VIN, CHR(13))",
  ROK_PRODUKCJI,
  PRZEBIEG_KM,
  POJEMNOSC_SILNIKA_CM3,
  MOC_KM
)
"@
  'p_72_typ_ubezpieczenia.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_typ_ubezpieczenia.csv'
INTO TABLE P_72_TYP_UBEZPIECZENIA
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_TYPU_UBEZPIECZENIA,
  NAZWA_TYPu "RTRIM(:NAZWA_TYPu, CHR(13))",
  OPIS "RTRIM(:OPIS, CHR(13))"
)
"@
  'p_72_ubezpieczenie.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_ubezpieczenie.csv'
INTO TABLE P_72_UBEZPIECZENIE
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_UBEZPIECZENIE,
  ID_TYPU_UBEZPIECZENIA,
  NUMER_POLISY "RTRIM(:NUMER_POLISY, CHR(13))",
  DATA_OD DATE "YYYY-MM-DD",
  DATA_DO DATE "YYYY-MM-DD",
  KWOTA_POKRYCIA,
  SKLADKA
)
"@
  'p_72_klient.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_klient.csv'
INTO TABLE P_72_KLIENT
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_KLIENT,
  IMIE "RTRIM(:IMIE, CHR(13))",
  NAZWISKO "RTRIM(:NAZWISKO, CHR(13))",
  PESEL "RTRIM(:PESEL, CHR(13))",
  TELEFON "RTRIM(:TELEFON, CHR(13))",
  EMAIL "RTRIM(:EMAIL, CHR(13))",
  NUMER_DOWODU "RTRIM(:NUMER_DOWODU, CHR(13))",
  NUMER_PRAWA_JAZDY "RTRIM(:NUMER_PRAWA_JAZDY, CHR(13))",
  KATEGORIA_PRAWA_JAZDY "RTRIM(:KATEGORIA_PRAWA_JAZDY, CHR(13))",
  DATA_WAZNOSCI_PRAWA_JAZDY DATE "YYYY-MM-DD",
  DATA_REJESTRACJI DATE "YYYY-MM-DD"
)
"@
  'p_72_wypozyczenia.ctl' = @"
OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_wypozyczenia.csv'
INTO TABLE P_72_WYPOZYCZENIA
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_SAMOCHOD,
  ID_KLIENT,
  ID_ODDZIAL_WYDANIA,
  ID_ODDZIAL_ODBIORU,
  ID_UBEZPIECZENIE,
  ID_PRACOWNIK_ODBIORU,
  ID_PRACOWNIK_WYDANIA,
  STATUS_WYPOZYCZENIA "RTRIM(:STATUS_WYPOZYCZENIA, CHR(13))",
  UWAGI "RTRIM(:UWAGI, CHR(13))",
  DATA_WYDANIA DATE "YYYY-MM-DD",
  DATA_PLANOWANEGO_ZWROTU DATE "YYYY-MM-DD",
  DATA_FAKTYCZNEGO_ZWROTU DATE "YYYY-MM-DD" NULLIF DATA_FAKTYCZNEGO_ZWROTU=BLANKS,
  KOSZT_TRANSPORTU,
  PRZEBIEG_START,
  PRZEBIEG_FINISH INTEGER EXTERNAL NULLIF PRZEBIEG_FINISH=BLANKS,
  PRZEBIEG_LIMIT,
  CENA_DOBA,
  CENA_RABAT_PROCENT,
  KAUCJA
)
"@
}

foreach ($entry in $templates.GetEnumerator()) {
  $target = Join-Path $ctlDir $entry.Key
  [System.IO.File]::WriteAllText($target, $entry.Value, [System.Text.UTF8Encoding]::new($false))
}

Write-Host "Generated $($templates.Count) CTL files in $ctlDir"
