-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-04-20 19:35:21 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE p_72_Kategoria 
    ( 
     ID_Kategoria        NUMBER (2)  NOT NULL , 
     Nazwa_Kategorii     VARCHAR2 (50 CHAR) , 
     Opis                VARCHAR2 (200 CHAR) , 
     Stawka_Bazowa_Netto NUMBER (12,2) 
    ) 
;

ALTER TABLE p_72_Kategoria 
    ADD CONSTRAINT p_72_Kategoria_PK PRIMARY KEY ( ID_Kategoria ) ;

CREATE TABLE p_72_Klient 
    ( 
     ID_Klient                 NUMBER (8)  NOT NULL , 
     Imie                      VARCHAR2 (50 CHAR) , 
     Nazwisko                  VARCHAR2 (80 CHAR) , 
     PESEL                     VARCHAR2 (11 CHAR) , 
     Telefon                   VARCHAR2 (20 CHAR) , 
     Email                     VARCHAR2 (100 CHAR) , 
     Numer_Dowodu              VARCHAR2 (20 CHAR) , 
     Numer_Prawa_Jazdy         VARCHAR2 (20 CHAR) , 
     Kategoria_Prawa_Jazdy     VARCHAR2 (10 CHAR) , 
     Data_Waznosci_Prawa_Jazdy DATE , 
     Data_Rejestracji          DATE 
    ) 
;

ALTER TABLE p_72_Klient 
    ADD CONSTRAINT p_72_Klient_PK PRIMARY KEY ( ID_Klient ) ;

ALTER TABLE p_72_Klient 
    ADD CONSTRAINT p_72_Klient_PESEL UNIQUE ( PESEL ) ;

CREATE TABLE p_72_Kolor 
    ( 
     ID_Kolor     NUMBER (3)  NOT NULL , 
     Nazwa_Koloru VARCHAR2 (30 CHAR) 
    ) 
;

ALTER TABLE p_72_Kolor 
    ADD CONSTRAINT p_72_Kolor_PK PRIMARY KEY ( ID_Kolor ) ;

CREATE TABLE p_72_Marka 
    ( 
     ID_Marka    NUMBER (3)  NOT NULL , 
     Nazwa_Marki VARCHAR2 (50 CHAR) 
    ) 
;

ALTER TABLE p_72_Marka 
    ADD CONSTRAINT p_72_Marka_PK PRIMARY KEY ( ID_Marka ) ;

CREATE TABLE p_72_Miasto 
    ( 
     ID_Miasta      NUMBER (5)  NOT NULL , 
     ID_Wojewodztwo NUMBER (2)  NOT NULL , 
     Nazwa_Miasta   VARCHAR2 (80 CHAR) 
    ) 
;

ALTER TABLE p_72_Miasto 
    ADD CONSTRAINT p_72_Miasto_PK PRIMARY KEY ( ID_Miasta ) ;

CREATE TABLE p_72_Model 
    ( 
     ID_Model     NUMBER (5)  NOT NULL , 
     Nazwa_Modelu VARCHAR2 (80 CHAR) , 
     ID_Marka     NUMBER (3)  NOT NULL 
    ) 
;

ALTER TABLE p_72_Model 
    ADD CONSTRAINT p_72_Model_PK PRIMARY KEY ( ID_Model ) ;

CREATE TABLE p_72_Oddzial 
    ( 
     ID_Oddzial       NUMBER (3)  NOT NULL , 
     Nazwa_Oddzialu   VARCHAR2 (80 CHAR) , 
     telefon          VARCHAR2 (20 CHAR) , 
     email            VARCHAR2 (100 CHAR) , 
     godziny_otwarcia VARCHAR2 (50 CHAR) , 
     Numer_Budynku    VARCHAR2 (10 CHAR) , 
     ID_Ulica         NUMBER (6)  NOT NULL , 
     Kod_Pocztowy     VARCHAR2 (10 CHAR) 
    ) 
;

ALTER TABLE p_72_Oddzial 
    ADD CONSTRAINT p_72_Oddzial_PK PRIMARY KEY ( ID_Oddzial ) ;

CREATE TABLE p_72_Panstwo 
    ( 
     ID_Panstwa    NUMBER (3)  NOT NULL , 
     Nazwa_Panstwa VARCHAR2 (80 CHAR) 
    ) 
;

ALTER TABLE p_72_Panstwo 
    ADD CONSTRAINT p_72_Panstwo_PK PRIMARY KEY ( ID_Panstwa ) ;

CREATE TABLE p_72_Pracownik 
    ( 
     ID_Pracownik      NUMBER (4)  NOT NULL , 
     ID_Oddzial        NUMBER (3)  NOT NULL , 
     ID_Stanowisko     NUMBER (2)  NOT NULL , 
     Imie              VARCHAR2 (50 CHAR) , 
     Nazwisko          VARCHAR2 (80 CHAR) , 
     PESEL             VARCHAR2 (11 CHAR) , 
     Telefon           VARCHAR2 (20 CHAR) , 
     Email             VARCHAR2 (100 CHAR) , 
     Data_Zatrudnienia DATE 
    ) 
;

ALTER TABLE p_72_Pracownik 
    ADD CONSTRAINT p_72_Pracownik_PK PRIMARY KEY ( ID_Pracownik ) ;

ALTER TABLE p_72_Pracownik 
    ADD CONSTRAINT p_72_Pracownik_PESEL UNIQUE ( PESEL ) ;

CREATE TABLE p_72_Samochod 
    ( 
     ID_Samochod           NUMBER (5)  NOT NULL , 
     ID_Oddzial            NUMBER (3)  NOT NULL , 
     ID_Typu_Paliwa        NUMBER (2)  NOT NULL , 
     ID_Kolor              NUMBER (3)  NOT NULL , 
     ID_Kategoria          NUMBER (2)  NOT NULL , 
     ID_Model              NUMBER (5)  NOT NULL , 
     ID_Typu_Skrzyni       NUMBER (2)  NOT NULL , 
     Numer_Rejestracyjny   VARCHAR2 (15 CHAR) , 
     Numer_VIN             VARCHAR2 (17 CHAR) , 
     Rok_Produkcji         NUMBER (4) , 
     Przebieg_Km           NUMBER (7) , 
     Pojemnosc_Silnika_cm3 NUMBER (5) , 
     Moc_Km                NUMBER (4) 
    ) 
;

ALTER TABLE p_72_Samochod 
    ADD CONSTRAINT p_72_Samochod_PK PRIMARY KEY ( ID_Samochod ) ;

ALTER TABLE p_72_Samochod 
    ADD CONSTRAINT p_72_Samochod_Numer_VIN_UN UNIQUE ( Numer_VIN ) ;

ALTER TABLE p_72_Samochod 
    ADD CONSTRAINT p_72_Sam_Nr_Rej_UN UNIQUE ( Numer_Rejestracyjny ) ;

CREATE TABLE p_72_Stanowisko 
    ( 
     ID_Stanowisko    NUMBER (2)  NOT NULL , 
     Nazwa_Stanowiska VARCHAR2 (60 CHAR) , 
     Opis             VARCHAR2 (200 CHAR) , 
     Stawka_Godzinowa NUMBER (8,2) 
    ) 
;

ALTER TABLE p_72_Stanowisko 
    ADD CONSTRAINT p_72_Stanowisko_PK PRIMARY KEY ( ID_Stanowisko ) ;

CREATE TABLE p_72_Typ_Paliwa 
    ( 
     ID_Typu_Paliwa NUMBER (2)  NOT NULL , 
     Nazwa_Paliwa   VARCHAR2 (30 CHAR) 
    ) 
;

ALTER TABLE p_72_Typ_Paliwa 
    ADD CONSTRAINT p_72_Typ_Paliwa_PK PRIMARY KEY ( ID_Typu_Paliwa ) ;

CREATE TABLE p_72_Typ_Skrzyni 
    ( 
     ID_Typu_Skrzyni NUMBER (2)  NOT NULL , 
     Nazwa_Skrzyni   VARCHAR2 (50 CHAR) 
    ) 
;

ALTER TABLE p_72_Typ_Skrzyni 
    ADD CONSTRAINT p_72_Typ_Skrzyni_PK PRIMARY KEY ( ID_Typu_Skrzyni ) ;

CREATE TABLE p_72_Typ_Ubezpieczenia 
    ( 
     ID_Typu_Ubezpieczenia NUMBER (2)  NOT NULL , 
     Nazwa_Typu            VARCHAR2 (80 CHAR) , 
     Opis                  VARCHAR2 (300 CHAR) 
    ) 
;

ALTER TABLE p_72_Typ_Ubezpieczenia 
    ADD CONSTRAINT p_72_Typ_Ubezpieczenia_PK PRIMARY KEY ( ID_Typu_Ubezpieczenia ) ;

CREATE TABLE p_72_Ubezpieczenie 
    ( 
     ID_Ubezpieczenie      NUMBER (8)  NOT NULL , 
     ID_Typu_Ubezpieczenia NUMBER (2)  NOT NULL , 
     Numer_Polisy          VARCHAR2 (30 CHAR) , 
     Data_Od               DATE , 
     Data_Do               DATE , 
     Kwota_Pokrycia        NUMBER (12,2) , 
     Skladka               NUMBER (10,2) 
    ) 
;

ALTER TABLE p_72_Ubezpieczenie 
    ADD CONSTRAINT p_72_Ubezpieczenie_PK PRIMARY KEY ( ID_Ubezpieczenie ) ;

CREATE TABLE p_72_Ulica 
    ( 
     ID_Ulica    NUMBER (6)  NOT NULL , 
     ID_Miasta   NUMBER (5)  NOT NULL , 
     Nazwa_Ulicy VARCHAR2 (100 CHAR) 
    ) 
;

ALTER TABLE p_72_Ulica 
    ADD CONSTRAINT p_72_Ulica_PK PRIMARY KEY ( ID_Ulica ) ;

CREATE TABLE p_72_Wojewodztwo 
    ( 
     ID_Wojewodztwo    NUMBER (2)  NOT NULL , 
     ID_Panstwa        NUMBER (3)  NOT NULL , 
     Nazwa_Wojewodztwa VARCHAR2 (80 CHAR) 
    ) 
;

ALTER TABLE p_72_Wojewodztwo 
    ADD CONSTRAINT p_72_Wojewodztwo_PK PRIMARY KEY ( ID_Wojewodztwo ) ;

CREATE TABLE p_72_Wypozyczenia 
    ( 
     ID_Samochod             NUMBER (5)  NOT NULL , 
     ID_Klient               NUMBER (8)  NOT NULL , 
     ID_Oddzial_Wydania      NUMBER (3)  NOT NULL , 
     ID_Oddzial_Odbioru      NUMBER (3)  NOT NULL , 
     ID_Ubezpieczenie        NUMBER (8)  NOT NULL , 
     ID_Pracownik_Odbioru    NUMBER (4)  NOT NULL , 
     ID_Pracownik_Wydania    NUMBER (4)  NOT NULL , 
     Status_Wypozyczenia     VARCHAR2 (50 CHAR) , 
     Uwagi                   VARCHAR2 (500 CHAR) , 
     Data_Wydania            DATE , 
     Data_Planowanego_Zwrotu DATE , 
     Data_Faktycznego_Zwrotu DATE , 
     Koszt_Transportu        NUMBER (8,2) , 
     Przebieg_Start          NUMBER (7) , 
     Przebieg_Finish         NUMBER (7) , 
     Przebieg_Limit          NUMBER (6) , 
     Cena_Doba               NUMBER (8,2) , 
     Cena_Rabat_Procent      NUMBER (5,2) , 
     Kaucja                  NUMBER (10,2) 
    ) 
;

ALTER TABLE p_72_Miasto 
    ADD CONSTRAINT p_72_Miasto_Wojewodztwo_FK FOREIGN KEY 
    ( 
     ID_Wojewodztwo
    ) 
    REFERENCES p_72_Wojewodztwo 
    ( 
     ID_Wojewodztwo
    ) 
;

ALTER TABLE p_72_Model 
    ADD CONSTRAINT p_72_Model_Marka_FK FOREIGN KEY 
    ( 
     ID_Marka
    ) 
    REFERENCES p_72_Marka 
    ( 
     ID_Marka
    ) 
;

ALTER TABLE p_72_Oddzial 
    ADD CONSTRAINT p_72_Oddzial_Ulica_FK FOREIGN KEY 
    ( 
     ID_Ulica
    ) 
    REFERENCES p_72_Ulica 
    ( 
     ID_Ulica
    ) 
;

ALTER TABLE p_72_Pracownik 
    ADD CONSTRAINT p_72_Pracownik_Oddzial_FK FOREIGN KEY 
    ( 
     ID_Oddzial
    ) 
    REFERENCES p_72_Oddzial 
    ( 
     ID_Oddzial
    ) 
;

ALTER TABLE p_72_Pracownik 
    ADD CONSTRAINT p_72_Pracownik_Stanowisko_FK FOREIGN KEY 
    ( 
     ID_Stanowisko
    ) 
    REFERENCES p_72_Stanowisko 
    ( 
     ID_Stanowisko
    ) 
;

ALTER TABLE p_72_Samochod 
    ADD CONSTRAINT p_72_Samochod_Kategoria_FK FOREIGN KEY 
    ( 
     ID_Kategoria
    ) 
    REFERENCES p_72_Kategoria 
    ( 
     ID_Kategoria
    ) 
;

ALTER TABLE p_72_Samochod 
    ADD CONSTRAINT p_72_Samochod_Kolor_FK FOREIGN KEY 
    ( 
     ID_Kolor
    ) 
    REFERENCES p_72_Kolor 
    ( 
     ID_Kolor
    ) 
;

ALTER TABLE p_72_Samochod 
    ADD CONSTRAINT p_72_Samochod_Model_FK FOREIGN KEY 
    ( 
     ID_Model
    ) 
    REFERENCES p_72_Model 
    ( 
     ID_Model
    ) 
;

ALTER TABLE p_72_Samochod 
    ADD CONSTRAINT p_72_Samochod_Oddzial_FK FOREIGN KEY 
    ( 
     ID_Oddzial
    ) 
    REFERENCES p_72_Oddzial 
    ( 
     ID_Oddzial
    ) 
;

ALTER TABLE p_72_Samochod 
    ADD CONSTRAINT p_72_Samochod_Typ_Paliwa_FK FOREIGN KEY 
    ( 
     ID_Typu_Paliwa
    ) 
    REFERENCES p_72_Typ_Paliwa 
    ( 
     ID_Typu_Paliwa
    ) 
;

ALTER TABLE p_72_Samochod 
    ADD CONSTRAINT p_72_Samochod_Typ_Skrzyni_FK FOREIGN KEY 
    ( 
     ID_Typu_Skrzyni
    ) 
    REFERENCES p_72_Typ_Skrzyni 
    ( 
     ID_Typu_Skrzyni
    ) 
;

ALTER TABLE p_72_Ubezpieczenie 
    ADD CONSTRAINT p_72_Ubezp_Typ_Ubezp_FK FOREIGN KEY 
    ( 
     ID_Typu_Ubezpieczenia
    ) 
    REFERENCES p_72_Typ_Ubezpieczenia 
    ( 
     ID_Typu_Ubezpieczenia
    ) 
;

ALTER TABLE p_72_Ulica 
    ADD CONSTRAINT p_72_Ulica_Miasto_FK FOREIGN KEY 
    ( 
     ID_Miasta
    ) 
    REFERENCES p_72_Miasto 
    ( 
     ID_Miasta
    ) 
;

ALTER TABLE p_72_Wojewodztwo 
    ADD CONSTRAINT p_72_Wojewodztwo_Panstwo_FK FOREIGN KEY 
    ( 
     ID_Panstwa
    ) 
    REFERENCES p_72_Panstwo 
    ( 
     ID_Panstwa
    ) 
;

ALTER TABLE p_72_Wypozyczenia 
    ADD CONSTRAINT p_72_Wypoz_Klient_FK FOREIGN KEY 
    ( 
     ID_Klient
    ) 
    REFERENCES p_72_Klient 
    ( 
     ID_Klient
    ) 
;

ALTER TABLE p_72_Wypozyczenia 
    ADD CONSTRAINT p_72_Wypoz_Odd_Od_FK FOREIGN KEY 
    ( 
     ID_Oddzial_Odbioru
    ) 
    REFERENCES p_72_Oddzial 
    ( 
     ID_Oddzial
    ) 
;

ALTER TABLE p_72_Wypozyczenia 
    ADD CONSTRAINT p_72_Wypoz_Odd_Wy_FK FOREIGN KEY 
    ( 
     ID_Oddzial_Wydania
    ) 
    REFERENCES p_72_Oddzial 
    ( 
     ID_Oddzial
    ) 
;

ALTER TABLE p_72_Wypozyczenia 
    ADD CONSTRAINT p_72_Wypoz_Pracow_Odbi_FK FOREIGN KEY 
    ( 
     ID_Pracownik_Odbioru
    ) 
    REFERENCES p_72_Pracownik 
    ( 
     ID_Pracownik
    ) 
;

ALTER TABLE p_72_Wypozyczenia 
    ADD CONSTRAINT p_72_Wypoz_Pracow_Wyd_FK FOREIGN KEY 
    ( 
     ID_Pracownik_Wydania
    ) 
    REFERENCES p_72_Pracownik 
    ( 
     ID_Pracownik
    ) 
;

ALTER TABLE p_72_Wypozyczenia 
    ADD CONSTRAINT p_72_Wypoz_Samochod_FK FOREIGN KEY 
    ( 
     ID_Samochod
    ) 
    REFERENCES p_72_Samochod 
    ( 
     ID_Samochod
    ) 
;

ALTER TABLE p_72_Wypozyczenia 
    ADD CONSTRAINT p_72_Wypoz_Ubezpieczenie_FK FOREIGN KEY 
    ( 
     ID_Ubezpieczenie
    ) 
    REFERENCES p_72_Ubezpieczenie 
    ( 
     ID_Ubezpieczenie
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            18
-- CREATE INDEX                             0
-- ALTER TABLE                             42
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
