OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_ubezpieczenie.csv'
INTO TABLE P_72_UBEZPIECZENIE
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_UBEZPIECZENIE,
  ID_TYPU_UBEZPIECZENIA,
  NUMER_POLISY "RTRIM(:NUMER_POLISY, CHR(13))",
  DATA_OD DATE "YYYY-MM-DD",
  DATA_DO DATE "YYYY-MM-DD",
  KWOTA_POKRYCIA,
  SKLADKA
)