OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_miasto.csv'
INTO TABLE P_72_MIASTO
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_MIASTA,
  ID_WOJEWODZTWO,
  NAZWA_MIASTA "RTRIM(:NAZWA_MIASTA, CHR(13))"
)