OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_klient.csv'
INTO TABLE P_72_KLIENT
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_KLIENT,
  IMIE,
  NAZWISKO,
  PESEL,
  TELEFON,
  EMAIL,
  NUMER_DOWODU,
  NUMER_PRAWA_JAZDY,
  KATEGORIA_PRAWA_JAZDY,
  DATA_WAZNOSCI_PRAWA_JAZDY DATE 'YYYY-MM-DD',
  DATA_REJESTRACJI DATE 'YYYY-MM-DD'
)
