OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_panstwo.csv'
INTO TABLE P_72_PANSTWO
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_PANSTWA,
  NAZWA_PANSTWA
)
