OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_typ_ubezpieczenia.csv'
INTO TABLE P_72_TYP_UBEZPIECZENIA
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_TYPU_UBEZPIECZENIA,
  NAZWA_TYPU,
  OPIS
)
