OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_klient.csv'
INTO TABLE P_72_KLIENT
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_KLIENT,
  IMIE "RTRIM(:IMIE, CHR(13))",
  NAZWISKO "RTRIM(:NAZWISKO, CHR(13))",
  PESEL "RTRIM(:PESEL, CHR(13))",
  TELEFON "RTRIM(:TELEFON, CHR(13))",
  EMAIL "RTRIM(:EMAIL, CHR(13))",
  NUMER_DOWODU "RTRIM(:NUMER_DOWODU, CHR(13))",
  NUMER_PRAWA_JAZDY "RTRIM(:NUMER_PRAWA_JAZDY, CHR(13))",
  KATEGORIA_PRAWA_JAZDY "RTRIM(:KATEGORIA_PRAWA_JAZDY, CHR(13))",
  DATA_WAZNOSCI_PRAWA_JAZDY DATE "YYYY-MM-DD",
  DATA_REJESTRACJI DATE "YYYY-MM-DD"
)