OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_oddzial.csv'
INTO TABLE P_72_ODDZIAL
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_ODDZIAL,
  NAZWA_ODDZIALU,
  TELEFON,
  EMAIL,
  GODZINY_OTWARCIA,
  NUMER_BUDYNKU,
  ID_ULICA,
  KOD_POCZTOWY
)
