OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_pracownik.csv'
INTO TABLE P_72_PRACOWNIK
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_PRACOWNIK,
  ID_ODDZIAL,
  ID_STANOWISKO,
  IMIE,
  NAZWISKO,
  PESEL,
  TELEFON,
  EMAIL,
  DATA_ZATRUDNIENIA DATE 'YYYY-MM-DD'
)
