OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_marka.csv'
INTO TABLE P_72_MARKA
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_MARKA,
  NAZWA_MARKI
)
