OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_kategoria.csv'
INTO TABLE P_72_KATEGORIA
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_KATEGORIA,
  NAZWA_KATEGORII,
  OPIS,
  STAWKA_BAZOWA_NETTO
)
