OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE '/tmp/sqlldr/csv/p_72_pracownik.csv'
INTO TABLE P_72_PRACOWNIK
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_PRACOWNIK,
  ID_ODDZIAL,
  ID_STANOWISKO,
  IMIE "RTRIM(:IMIE, CHR(13))",
  NAZWISKO "RTRIM(:NAZWISKO, CHR(13))",
  PESEL "RTRIM(:PESEL, CHR(13))",
  TELEFON "RTRIM(:TELEFON, CHR(13))",
  EMAIL "RTRIM(:EMAIL, CHR(13))",
  DATA_ZATRUDNIENIA DATE "YYYY-MM-DD"
)