OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE 'csv/p_72_kolor.csv'
INTO TABLE P_72_KOLOR
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_KOLOR,
  NAZWA_KOLORU "RTRIM(:NAZWA_KOLORU, CHR(13))"
)