OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE 'csv/p_72_oddzial.csv'
INTO TABLE P_72_ODDZIAL
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_ODDZIAL,
  NAZWA_ODDZIALU "RTRIM(:NAZWA_ODDZIALU, CHR(13))",
  TELEFON "RTRIM(:TELEFON, CHR(13))",
  EMAIL "RTRIM(:EMAIL, CHR(13))",
  GODZINY_OTWARCIA "RTRIM(:GODZINY_OTWARCIA, CHR(13))",
  NUMER_BUDYNKU "RTRIM(:NUMER_BUDYNKU, CHR(13))",
  ID_ULICA,
  KOD_POCZTOWY "RTRIM(:KOD_POCZTOWY, CHR(13))"
)