OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE 'csv/p_72_samochod.csv'
INTO TABLE P_72_SAMOCHOD
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_SAMOCHOD,
  ID_ODDZIAL,
  ID_TYPU_PALIWA,
  ID_KOLOR,
  ID_KATEGORIA,
  ID_MODEL,
  ID_TYPU_SKRZYNI,
  NUMER_REJESTRACYJNY "RTRIM(:NUMER_REJESTRACYJNY, CHR(13))",
  NUMER_VIN "RTRIM(:NUMER_VIN, CHR(13))",
  ROK_PRODUKCJI,
  PRZEBIEG_KM,
  POJEMNOSC_SILNIKA_CM3,
  MOC_KM
)