OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE 'csv/p_72_wypozyczenia.csv'
INTO TABLE P_72_WYPOZYCZENIA
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_SAMOCHOD,
  ID_KLIENT,
  ID_ODDZIAL_WYDANIA,
  ID_ODDZIAL_ODBIORU,
  ID_UBEZPIECZENIE,
  ID_PRACOWNIK_ODBIORU,
  ID_PRACOWNIK_WYDANIA,
  STATUS_WYPOZYCZENIA "RTRIM(:STATUS_WYPOZYCZENIA, CHR(13))",
  UWAGI "RTRIM(:UWAGI, CHR(13))",
  DATA_WYDANIA DATE "YYYY-MM-DD",
  DATA_PLANOWANEGO_ZWROTU DATE "YYYY-MM-DD",
  DATA_FAKTYCZNEGO_ZWROTU DATE "YYYY-MM-DD" NULLIF DATA_FAKTYCZNEGO_ZWROTU=BLANKS,
  KOSZT_TRANSPORTU,
  PRZEBIEG_START,
  PRZEBIEG_FINISH INTEGER EXTERNAL NULLIF PRZEBIEG_FINISH=BLANKS,
  PRZEBIEG_LIMIT,
  CENA_DOBA,
  CENA_RABAT_PROCENT,
  KAUCJA
)