OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE 'csv/p_72_typ_ubezpieczenia.csv'
INTO TABLE P_72_TYP_UBEZPIECZENIA
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_TYPU_UBEZPIECZENIA,
  NAZWA_TYPu "RTRIM(:NAZWA_TYPu, CHR(13))",
  OPIS "RTRIM(:OPIS, CHR(13))"
)