OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE 'csv/p_72_typ_paliwa.csv'
INTO TABLE P_72_TYP_PALIWA
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_TYPU_PALIWA,
  NAZWA_PALIWA "RTRIM(:NAZWA_PALIWA, CHR(13))"
)