OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE 'csv/p_72_model.csv'
INTO TABLE P_72_MODEL
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_MODEL,
  NAZWA_MODELU "RTRIM(:NAZWA_MODELU, CHR(13))",
  ID_MARKA
)