OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE 'csv/p_72_ulica.csv'
INTO TABLE P_72_ULICA
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_ULICA,
  ID_MIASTA,
  NAZWA_ULICY "RTRIM(:NAZWA_ULICY, CHR(13))"
)