OPTIONS (SKIP=0, ERRORS=100000)
LOAD DATA
INFILE 'csv/p_72_wojewodztwo.csv'
INTO TABLE P_72_WOJEWODZTWO
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID_WOJEWODZTWO,
  ID_PANSTWA,
  NAZWA_WOJEWODZTWA "RTRIM(:NAZWA_WOJEWODZTWA, CHR(13))"
)